# Generated by Django 4.0.3 on 2022-04-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='Patient',
        ),
    ]
